# The two files combined in one
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80 # External port will be mapped to the internal port 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5 # number of pods to run
  selector:
    matchLabels:
      app: nginx # which pods are managed by this deployment
  template:
    metadata:
      labels:
        app: nginx # labels for pods managed by this deployment
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
# more info here: https://kubernetes.io/docs/reference/kubernetes-api/
