apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-hello
  ports:
    - port: 3030 # port where the service is listening
      targetPort: 3000 # port where the container is listening
